### ISSUE TITLE
Failed to list OpenCL platforms.

### ISSUE THREAD

**Issue by maccloud42** [todxx/teamredminer#244]
AMD® Ryzen threadripper 1900x 8-core processor × 16
Radeon RX 580 Series (POLARIS10, DRM 3.38.0, 5.8.0-44-generic, LLVM 11.0.0)

selected clinfo output:
    Platform Version:				 OpenCL 2.0 AMD-APP (3212.0)
    Number of devices:				 2

    Device Type:			        CL_DEVICE_TYPE_GPU
    Vendor ID:					1002h
    Board name:				Vega 10 XL/XT [Radeon RX Vega 56/64]
    Platform ID:					 0x7f4c79d9dcf0
    Name:						 gfx900
    Vendor:					 Advanced Micro Devices, Inc.
    Device OpenCL C version:		 OpenCL C 2.0 
    Driver version:				 3212.0 (HSA1.1,LC)
    Profile:					 FULL_PROFILE
    Version:					 OpenCL 2.0 

    Device Type:				 CL_DEVICE_TYPE_GPU
    Vendor ID:					 1002h
    Board name:			         Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (4096 MB)
    Platform ID:					 0x7f4c79d9dcf0
    Name:						 gfx803
    Vendor:					 Advanced Micro Devices, Inc.
    Device OpenCL C version:	         OpenCL C 2.0 
    Driver version:				 3212.0 (HSA1.1,LC)
    Profile:					 FULL_PROFILE
    Version:					 OpenCL 1.2 

Screen HTML output:
<pre><font color="#8AE234"><b>a@a-MS-7B09</b></font>:<font color="#729FCF"><b>~/Desktop/teamredminer-v0.8.1-linux</b></font>$ ./start_eth_4gb.sh
          Team Red Miner version 0.8.1
[2021-03-14 15:39:19] <font color="#FCE94F"><b>Pool eu1.ethermine.org: Ethermine ethash auto mode detected, setting --eth_stratum=ethproxy</b></font>
[2021-03-14 15:39:19] <font color="#EF2929"><b>Failed to list OpenCL platforms.</b></font>
[2021-03-14 15:39:19] Successful clean shutdown.
<font color="#8AE234"><b>a@a-MS-7B09</b></font>:<font color="#729FCF"><b>~/Desktop/teamredminer-v0.8.1-linux</b></font>$ ./start_eth.sh
          Team Red Miner version 0.8.1
[2021-03-14 15:39:25] <font color="#FCE94F"><b>Pool eu1.ethermine.org: Ethermine ethash auto mode detected, setting --eth_stratum=ethproxy</b></font>
[2021-03-14 15:39:25] <font color="#EF2929"><b>Failed to list OpenCL platforms.</b></font>
[2021-03-14 15:39:25] Successful clean shutdown.
<font color="#8AE234"><b>a@a-MS-7B09</b></font>:<font color="#729FCF"><b>~/Desktop/teamredminer-v0.8.1-linux</b></font>$ 

</pre>

**Comment by kachapman** [comment]
Im having the same issue. Pop!_OS 20.10, RX480 8GB Polaris, AMDGPU drivers.

**Comment by 3mmo** [comment]
Same here with Ubuntu 20.04.2 LTS
AMD Ryzen 7 3800X 8-Core Processor
Radeon RX5700 XT

some clinfo output:
```
Number of platforms:                             1                                                  
  Platform Profile:                              FULL_PROFILE                                       
  Platform Version:                              OpenCL 2.0 AMD-APP (3212.0)                        
  Platform Name:                                 AMD Accelerated Parallel Processing                
  Platform Vendor:                               Advanced Micro Devices, Inc.                       
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback                   
                                                                                                    
                                                                                                    
  Platform Name:                                 AMD Accelerated Parallel Processing                
Number of devices:                               1                                                  
  Device Type:                                   CL_DEVICE_TYPE_GPU                                 
  Vendor ID:                                     1002h                                              
  Board name:                                    Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]

```
Let me know if you need more details

**Comment by naldertown** [comment]
Same issue here - Ubuntu 20.04 running rocm. 

`Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP (3212.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback 
  Platform Extensions function suffix             AMD
`
2 Radeon RX5500 XT GPUs

**Comment by naldertown** [comment]
@maccloud42 @3mmo @kachapman I have fixed this issue. The solution was:

Update the icd reference in `/etc/OpenCL/vendors/amdocl64_40000.icd` with the correct path to the icd. In my case it was updating `libamdocl64.so` to `/opt/rocm/opencl/lib/libamdocl64.so`.

Hope that helps someone.

**Comment by kachapman** [comment]
I noticed that you are using the program 'clinfo' to gather information about the platform. I just installed that program and Im getting this output:

> Number of platforms                               0

**Comment by naldertown** [comment]
@kachapman Looks like you don't have opencl working - so the GPUs won't be available to compute. You need to install AMDGPU pro or ROCm or suchlike to get it working.

**Comment by maccloud42** [comment]
> @maccloud42 @3mmo @kachapman I have fixed this issue. The solution was:
> 
> Update the icd reference in `/etc/OpenCL/vendors/amdocl64_40000.icd` with the correct path to the icd. In my case it was updating `libamdocl64.so` to `/opt/rocm/opencl/lib/libamdocl64.so`.
> 
> Hope that helps someone.

Brilliant, this is the fix. Edit /etc/OpenCL/vendors/amdocl64_40000.icd to reference /opt/rocm/opencl/lib/libamdocl64.so instead of /etc/OpenCL/vendors/libamdocl64.so
or
cp /opt/rocm/opencl/lib/libamdocl64.so /etc/OpenCL/vendors/

or better still

sudo ln -s  /etc/OpenCL/vendors/amdocl64.so  /opt/rocm/opencl/lib/libamdocl64.so

Working like a dream now. Thankyou so much

**Comment by kachapman** [comment]
Im still getting the original error.
I installed ROCm. Here is the output of clinfo:

> Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP (3212.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_event_callback 
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  No platform
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   No platform
  clCreateContext(NULL, ...) [default]            No platform
  clCreateContext(NULL, ...) [other]              No platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

**Comment by brunobliss** [comment]
> 
> 
> > @maccloud42 @3mmo @kachapman I have fixed this issue. The solution was:
> > Update the icd reference in `/etc/OpenCL/vendors/amdocl64_40000.icd` with the correct path to the icd. In my case it was updating `libamdocl64.so` to `/opt/rocm/opencl/lib/libamdocl64.so`.
> > Hope that helps someone.
> 
> Brilliant, this is the fix. Edit /etc/OpenCL/vendors/amdocl64_40000.icd to reference /opt/rocm/opencl/lib/libamdocl64.so instead of /etc/OpenCL/vendors/libamdocl64.so
> or
> cp /opt/rocm/opencl/lib/libamdocl64.so /etc/OpenCL/vendors/
> 
> or better still
> 
> sudo ln -s /etc/OpenCL/vendors/amdocl64.so /opt/rocm/opencl/lib/libamdocl64.so
> 
> Working like a dream now. Thankyou so much

what about windows users? what to edit ??

**Comment by MrZappas** [comment]
Found solution on windows:
Open file register editor, locate KEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Khronos\OpenCL\Vendors  there's just one file.
Now open and browse your windows files to: C:\Windows\System32\DriverStore\FileRepository\  and search for amdocl64.dll  now that you get the real amdocl64.dll folder and address, copy it and go back to registry editor, create a new path as the one found before, with just the correct address of amdocl64.dll just found. 
Delete the old amdocl64.dll file path from the registry and go back and run team red miner as smooth as .... :D

**Comment by pbrewczynski** [comment]
> > @maccloud42 @3mmo @kachapman I have fixed this issue. The solution was:
> > Update the icd reference in `/etc/OpenCL/vendors/amdocl64_40000.icd` with the correct path to the icd. In my case it was updating `libamdocl64.so` to `/opt/rocm/opencl/lib/libamdocl64.so`.
> > Hope that helps someone.
> 
> Brilliant, this is the fix. Edit /etc/OpenCL/vendors/amdocl64_40000.icd to reference /opt/rocm/opencl/lib/libamdocl64.so instead of /etc/OpenCL/vendors/libamdocl64.so or cp /opt/rocm/opencl/lib/libamdocl64.so /etc/OpenCL/vendors/
> 
> or better still
> 
> sudo ln -s /etc/OpenCL/vendors/amdocl64.so /opt/rocm/opencl/lib/libamdocl64.so
> 
> Working like a dream now. Thankyou so much

It should be other way around :  sudo ln -s  /opt/rocm/opencl/lib/libamdocl64.so /etc/OpenCL/vendors/amdocl64.so  
(Syntax : ln -s Existing-file New-name)

Unfortunately I still get Failed to list OpenCL devices for platform 0. 
I run linux mint with rx580 and I ran amdgpu-install
